### PR TITLE
Perceive object keywords

### PR DESCRIPTION
**Pull request by fairlight1337**
Incorporates changes to the plan `perceive-objects` as addressed in https://github.com/cram2/cram_plans/pull/3.

### CODE REVIEW

**Comment by fairlight1337** [comment]
Sorry about all the merge commits.

**Comment by gaya-** [comment]
@fairlight1337 https://github.com/code-iai/longterm_fetch_and_place/blob/master/ltfnp_executive/src/utils.lisp#L113

**Comment by fairlight1337** [comment]
Ah yes, thanks. Done. Its now part of https://github.com/code-iai/longterm_fetch_and_place/pull/14.

**Comment by gaya-** [comment]
Also, FYI
https://github.com/cram2/cram_plans/commit/94898041d856ccab806002a1a34b362e72ace050

**Pull request merged**
