### PR TITLE
Several fixes to models, reasoning, kitchen environment

### PR DESCRIPTION
**Pull request by fairlight1337**

### CODE REVIEW

**Comment by bbrieber** [comment]
The pathToURDFModel property is not fully specified I would recommend to add some restrictions to it.

**Comment by fairlight1337** [comment]
@bbrieber Restrictions such as being an `xsd:string`? The property definition is missing at the moment, that's right. Maybe we can add it to whereever `pathToCadModel` is defined (@daniel86?).

**Comment by daniel86** [comment]
@fairlight1337 sure that should not cause any issues, I can do that

**Comment by daniel86** [comment]
@bbrieber , @fairlight1337 the range of pathToCadModel is already restricted to xsd:string

**Comment by fairlight1337** [comment]
@daniel86 Can you add the same for `pathToURDFModel` as well at the same spot?

**Pull request merged**
